version: "3.8"

services:
  db:
    image: postgres:16
    container_name: sitelog-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: drngeary
      POSTGRES_PASSWORD: castlefinn13!
      POSTGRES_DB: sitelogdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
